name: Run Web Scraper

on:
  schedule:
    # Runs every day at 09:00 UTC
    - cron: "0 9 * * *"
  workflow_dispatch:   # allow manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        run: python main.py
