name: Agoda Flight Scraper

on:
  schedule:
    # 19:00 UTC = 02:00 AM Thailand
    - cron: "0 19 * * *"
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install chromium

      - name: Run scraper
        run: python main.py

      - name: Upload CSV as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: agoda-flights-${{ github.run_id }}
          path: agoda_flights_direct_full_V43.csv
